### PR TITLE
Fix bug in cache invalidation

### LINKED ISSUE #13: bug in cache invalidation
**Describe the bug**
Changes to cache invalidation logic introduced bug. The path tsv file not properly configured in the code.

**To Reproduce**
Kick off run for germline analysis:
```
cubi-tk snappy kickoff
```

**Additional context**
Error message:
```
ESC[31mRuleException:
FileNotFoundError in line 52 of /path/to/dev/snappy/snappy_pipeline/workflows/ngs_mapping/Snakefile:
[Errno 2] No such file or directory: '2021_<project_name>.tsv'
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2317, in run_wrapper
  File "/path/to/dev/snappy/snappy_pipeline/workflows/ngs_mapping/Snakefile", line 52, in __rule_ngs_mapping_link_in_run
  File "/path/to/dev/snappy/snappy_pipeline/workflows/abstract/__init__.py", line 641, in get_shell_cmd
  File "/path/to/dev/snappy/snappy_pipeline/workflows/abstract/__init__.py", line 660, in substep_dispatch
  File "/path/to/dev/snappy/snappy_pipeline/workflows/abstract/__init__.py", line 852, in get_shell_cmd
  File "/path/to/dev/snappy/snappy_pipeline/workflows/abstract/__init__.py", line 739, in run
  File "/path/to/dev/snappy/snappy_pipeline/find_file.py", line 133, in run
  File "/path/to/dev/snappy/snappy_pipeline/find_file.py", line 209, in _perform_cache_invalidation
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/genericpath.py", line 55, in getmtime
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 566, in _callback
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 552, in cached_or_run
  File "/path/to/project/work/miniconda3.barbosae_c/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2348, in run_wrapperESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
Shutting down, this might take some time.
02-24 15:48 snakemake.logging WARNING  Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
02-24 15:48 snakemake.logging ERROR    Exiting because a job execution failed. Look above for error message
```

### PR DESCRIPTION
**Pull request by eudesbarbosa**
closes #13 

**Summary**

Fixed bug while defining path to sample sheet (e.g., `2021_<project_name>.tsv`) before invalidating cache.

### CODE REVIEW

**Comment by eudesbarbosa** [comment]
@holtgrewe, I added a `os.walk()` to look for the sheet file cause couldn't find any easier source in `LinkInPathGenerator`. 
Hopefully it won't affect too much the performance as the base dirs are just the working directory and the `.snappy_pipeline`.

**Comment by eudesbarbosa** [comment]
`os.walk()` is not an option in production, changed it to `os.listdir()`.

**Comment by holtgrewe** [comment]
Is this a draft? If so please mark as such ;-)

**Comment by eudesbarbosa** [comment]
It should be good to go. I briefly changed it to draft in the middle of the day, but it is working fine now.

**Review by holtgrewe — APPROVED** [review]
LGTM, please merge with squash.

**Pull request merged**
