### PR TITLE
Collecting depth of coverage in ngs_mapping (#206)

### PR DESCRIPTION
**Pull request by holtgrewe**

### CODE REVIEW

**Review by eudesbarbosa — CHANGES_REQUESTED** [review]
Looks good. Two points:
1. Unit tests need to be adjusted to include the new step.
2. It seems like `maelstrom-core` was independently installed (?). If yes, it is probably worth including a note in the Installation Readme|Documentation. Not sure how that would look like.

**Comment by holtgrewe** [comment]
Thanks. Good points, somehow the tests got lost between my local and the HPC checkout. Will add now.

Regarding maelstrom, I need to make a bioconda release. Will ping when this is done.

**Comment by holtgrewe** [comment]
OK, this is pending https://github.com/bioconda/bioconda-recipes/pull/36971 but then good to go.

**Review by eudesbarbosa — APPROVED** [review]
LGTM

**Pull request merged**
