### PR TITLE
Add Delly to WGS CNV Calling workflow

### PR DESCRIPTION
**Pull request by eudesbarbosa**
**Changes**
* Added Delly to WGS CNV calling workflow.

### CODE REVIEW

**Comment by eudesbarbosa** [comment]
WIP: Problem with intermediate step, final VCF has no entries.

**Comment by eudesbarbosa** [comment]
Problem: All entries tagged as 'IMPRECISE' and ignored by `reorder_vcf` step: `--include '(GT !~ "\.") && (GT ~ "1")'`

**Comment by eudesbarbosa** [comment]
On hold until #189 is complete: `reorder_vcf` wrapper removed.

**Review by holtgrewe — APPROVED** [review]
LGTM

**Pull request merged**
